import { jsPDF } from 'jspdf';
import { autoTable } from 'jspdf-autotable';
import { getCategoryDisplayLabel, getTransactionType } from '@/lib/constants';
import { formatCurrency } from '@/lib/currency';

const TEKSQUAD_URL = 'https://teksquad.tech/';

function formatStatementDate(date) {
    if (!date) return '—';
    const d = date instanceof Date ? date : new Date(date);
    return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
}

function formatMonthYearForFilename(startDate) {
    const d = startDate instanceof Date ? startDate : new Date(startDate);
    const month = d.toLocaleString('en-US', { month: 'short' });
    return `${month}${d.getFullYear()}`;
}

/**
 * Centered gray footer on every page after the PDF is fully composed (all pages exist).
 * Uses `textWithLink` when present so the TekSquad URL is clickable.
 * @param {object} doc jsPDF instance
 */
function addBrandedFootersToAllPages(doc) {
    const pageCount = doc.getNumberOfPages();
    const pageW = doc.internal.pageSize.getWidth();
    const pageH = doc.internal.pageSize.getHeight();
    const y = pageH - 8;
    const partA = 'Generated by Excalper | Powered by TekSquad (';
    const urlText = TEKSQUAD_URL;
    const partB = ')';

    for (let i = 1; i <= pageCount; i += 1) {
        doc.setPage(i);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(7);
        doc.setTextColor(120, 120, 120);

        const hasLink = typeof doc.textWithLink === 'function';
        const wA = doc.getTextWidth(partA);
        const wU = doc.getTextWidth(urlText);
        const wB = doc.getTextWidth(partB);
        const totalW = wA + wU + wB;
        let x = (pageW - totalW) / 2;

        doc.text(partA, x, y);
        x += wA;

        if (hasLink) {
            doc.textWithLink(urlText, x, y, { url: TEKSQUAD_URL });
        } else {
            doc.text(urlText, x, y);
        }
        x += wU;
        doc.text(partB, x, y);
    }
}

/**
 * @param {Array<Record<string, unknown>>} transactions
 * @param {{ startDate: Date, endDate: Date }} cycleDates
 * @param {{ displayName?: string, email?: string, currency?: string }} userProfile
 * @param {{ documentTitle?: string, fileName?: string }} [options]
 */
export function generateMonthlyStatement(transactions, cycleDates, userProfile, options = {}) {
    const { startDate, endDate } = cycleDates;
    const currencyCode = userProfile?.currency || 'GBP';
    const displayName = userProfile?.displayName || 'User';
    const email = userProfile?.email || '';

    const documentTitle = options.documentTitle ?? 'Monthly Financial Statement';
    const fileName =
        options.fileName ?? `Excalper_Statement_${formatMonthYearForFilename(startDate)}.pdf`;

    const sorted = [...transactions].sort((a, b) => {
        const da = a.date instanceof Date ? a.date : a.date ? new Date(a.date) : new Date(0);
        const db = b.date instanceof Date ? b.date : b.date ? new Date(b.date) : new Date(0);
        return da - db;
    });

    let totalIncome = 0;
    let totalExpenses = 0;
    for (const t of sorted) {
        const type = getTransactionType(t);
        const amt = Number(t.amount) || 0;
        if (type === 'income') {
            totalIncome += amt;
        } else {
            totalExpenses += amt;
        }
    }
    const netCashFlow = totalIncome - totalExpenses;

    const doc = new jsPDF({ unit: 'mm', format: 'a4' });
    const pageW = doc.internal.pageSize.getWidth();
    const margin = 20;

    const rangeLabel = `${formatStatementDate(startDate)} - ${formatStatementDate(endDate)}`;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(22);
    doc.setTextColor(15, 23, 42);
    doc.text('Excalper', margin, 20);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139);
    const accountLine = email ? `${displayName} · ${email}` : displayName;
    doc.text(accountLine, margin, 26);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42);
    doc.text(documentTitle, pageW - margin - doc.getTextWidth(documentTitle), 18);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(71, 85, 105);
    doc.text(rangeLabel, pageW - margin - doc.getTextWidth(rangeLabel), 25);

    const summaryTop = 34;
    const summaryH = 30;
    doc.setFillColor(248, 250, 252);
    doc.setDrawColor(226, 232, 240);
    doc.roundedRect(margin, summaryTop, pageW - 2 * margin, summaryH, 2, 2, 'FD');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(15, 23, 42);
    doc.text('Summary', margin + 4, summaryTop + 7);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    let sy = summaryTop + 14;
    doc.setTextColor(22, 101, 52);
    doc.text(`Total Income: ${formatCurrency(totalIncome, currencyCode)}`, margin + 4, sy);
    sy += 6;
    doc.setTextColor(185, 28, 28);
    doc.text(`Total Expenses: ${formatCurrency(totalExpenses, currencyCode)}`, margin + 4, sy);
    sy += 6;
    doc.setTextColor(15, 23, 42);
    doc.text(`Net Cash Flow: ${formatCurrency(netCashFlow, currencyCode)}`, margin + 4, sy);

    const tableBody = sorted.map((t) => {
        const type = getTransactionType(t);
        const rawAmount = Number(t.amount) || 0;
        const categoryLabel = getCategoryDisplayLabel(t.category ?? t.paymentMode);
        const dateStr = formatStatementDate(t.date);
        const desc = String(t.description ?? '').slice(0, 80) || '—';
        const amountStr =
            type === 'income'
                ? formatCurrency(rawAmount, currencyCode)
                : `-${formatCurrency(rawAmount, currencyCode)}`;

        return [dateStr, desc, categoryLabel, amountStr];
    });

    autoTable(doc, {
        startY: summaryTop + summaryH + 8,
        head: [['Date', 'Description', 'Category', 'Amount']],
        body: tableBody.length ? tableBody : [['—', 'No transactions in this period', '—', '—']],
        theme: 'striped',
        styles: {
            fontSize: 9,
            cellPadding: 3,
            textColor: [15, 23, 42],
        },
        headStyles: {
            fillColor: [15, 23, 42],
            textColor: 255,
            fontStyle: 'bold',
            fontSize: 9,
        },
        alternateRowStyles: { fillColor: [248, 250, 252] },
        columnStyles: {
            0: { cellWidth: 28 },
            1: { cellWidth: 'auto' },
            2: { cellWidth: 36 },
            3: { cellWidth: 32, halign: 'right' },
        },
        margin: { left: margin, right: margin },
    });

    addBrandedFootersToAllPages(doc);
    doc.save(fileName);
}
